### ISSUE TITLE
如何配置发送邮件的SMTP的配置

### ISSUE THREAD

**Issue by zhengmingliang** [PGYER/codefever#142]
![image](https://user-images.githubusercontent.com/16442564/219265603-c6747460-8702-4d00-a866-fa5ce38591f2.png)
SMTP发信的邮箱配置在什么地方啊，配置文件的模板文件里也没找到对应的key，该如何配置呢？

 config.template.yaml
```yaml
---
host: http://local.alianga.com:8780
ssh: 'git@localhost:'
allowRegister: false
email:
  name: CodeFever Community
  from: service@alianga.com
...

```
